### ISSUE TITLE
Missing mounting directory in 1.3 Using Kickstart files

### ISSUE THREAD

**Issue by dgpmakes** [jadebustos/workshops-rhel9#1]
###### In [https://jadebustos.github.io/workshops-rhel9/workshops-rhel9/01-installation-using-ks.html](url), that uses doc [https://github.com/jadebustos/workshops-rhel9/blob/master/documentation/modules/ROOT/pages/01-installation-using-ks.adoc](url).

Inside the **Using kickstart files from within a DVD ISO** section, it is needed to:

- `mount -t iso9660 /root/rhel-baseos-9.0-x86_64-dvd.iso /media/isos -o loop`

But doing this returns "mounting point does not exist".
Therefore to solve it is needed to create the mounting directory before mounting:

1. `mkdir /media/isos`

2. `mount -t iso9660 /root/rhel-baseos-9.0-x86_64-dvd.iso /media/isos -o loop`

**Comment by jadebustos** [comment]
Pull request sent by dgpMakes
